In [65]:
import numpy as np

1. Write a function so that the columns of the output matrix are powers of the input vector.
   The order of the powers is determined by the increasing boolean argument. Specifically, when
   increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [23]:
vector1=np.array([1,2,4,5])
N=3

In [33]:
def gen_vander_matrix(vector1, N, increasing):
    
    if not increasing:
        op_matx = np.array([x**(N-1-i) for x in vector1 for i in range(N)]).reshape(vector1.size,N)
    else:
        op_matx = np.array([x**i for x in vector1 for i in range(N)]).reshape(vector1.size,N)
    
    return op_matx

In [41]:
print("vander matrix in decreasing order \n",gen_vander_matrix(vector1,N,False))

vander matrix in decreasing order 
 [[ 1  1  1]
 [ 4  2  1]
 [16  4  1]
 [25  5  1]]


In [40]:
print("vander matirx in increasing order \n",gen_vander_matrix(vector1,N,True))

vander matirx in increasing order 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  4 16]
 [ 1  5 25]]


In [ ]:
2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
   the given sequence is defined as follows:
   The moving average sequence has n-k+1 elements as shown below.
   The moving averages with k=4 of a ten-value sequence (n=10) is shown below
   i 1 2 3 4 5 6 7 8 9 10
   ===== == == == == == == == == == ==
   Input 10 20 30 40 50 60 70 80 90 100
   y1 25 = (10+20+30+40)/4
   y2 35 = (20+30+40+50)/4
   y3 45 = (30+40+50+60)/4
   y4 55 = (40+50+60+70)/4
   y5 65 = (50+60+70+80)/4
   y6 75 = (60+70+80+90)/4
   y7 85 = (70+80+90+100)/4
   Thus, the moving average sequence has n-k+1=10-4+1=7 values.
   Write a function to find moving average in an array over a window:
   Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [107]:
def movingavg(x,k):
    z=len(x)-k+1
    ls=[]
    for n in range(z):
        avg=0
        sum1=0
        for i in range(k):
            sum1=sum1+x[n+i]
            avg=sum1/k
        ls.append(avg)
    return ls
x=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
print("k th moving averge of the given seq:- \n",np.array(movingavg(x,k)).round(2))

k th moving averge of the given seq:- 
 [  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]


method 2:- using the numpy
        cumsum function used for find the commulative sum

In [ ]:
  Write a function to find moving average in an array over a window:
  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [109]:
def moving_average(a,n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(np.array(moving_average(x, n=3)).round(2))

[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
